run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/kumityou/teamflow
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: unexported-return
        disabled: true
      - name: blank-imports
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: errorf
        disabled: false
  gosec:
    excludes:
      - G104 # Unhandled errors (covered by errcheck)

issues:
  exclude-dirs:
    - apps/tasks/internal/infrastructure/task/sqlc
  exclude-rules:
    # Disable certain linters for test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Disable exported rules for test utility packages
    - path: testutil/
      linters:
        - revive
      text: "exported:"
